CREATE DATABASE AlZain_Company_DATA;
USE AlZain_Company_DATA;
CREATE TABLE CUSTMER
(
GUID_CU UNIQUEIDENTIFIER,
ID_CU INT PRIMARY KEY,
NAME_CU NVARCHAR(MAX) NOT NULL,
PHONE NVARCHAR(255) NOT NULL,
ADRIS NVARCHAR(255) NOT NULL,
DATAPERTH NVARCHAR(200),
TYPEPR NVARCHAR(50),
IMGS_CU IMAGE
);

CREATE TABLE PRODUCT(
GUID_PRO UNIQUEIDENTIFIER,
ID_PRO INT PRIMARY KEY,
TYPE_PRO NVARCHAR (255),
NAME_PRO NVARCHAR(MAX)NOT NULL,
NAME_BR NVARCHAR(MAX) NOT NULL,
COUNT_PRO INT ,
PRICEBUY_PRO INT NOT NULL,
PRICEBAY_PRO INT NOT NULL,
IMGE_PRO IMAGE,

);
CREATE TABLE INVOICE (
GUID_INV UNIQUEIDENTIFIER,
ID_INVOICE INT PRIMARY KEY,
ID_CUSTMER INT FOREIGN KEY REFERENCES CUSTMER (ID_CU),
ID_PRODUCT INT FOREIGN KEY REFERENCES PRODUCT (ID_PRO),
COUNT_PRO INT ,
DATA_INV NVARCHAR(200),
TOTAL_INV INT ,
VALUE_PAID INT,
REST_INV INT,
ACCONT NVARCHAR(200)
);
UPDATE PRODUCT
                      SET COUNT_PRO = 2
                      WHERE ID_PRO =1 
select*from PRODUCT
DROP TABLE INVOICE;

